server:
  port: 8080

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    routes:
      - id: user_service_route
        uri: lb://USER-SERVICE
        predicates:
          - Path=/api/users/**
        filters:
          - StripPrefix=1
